import type { Metadata } from "next";
import { JetBrains_Mono} from "next/font/google";
import {Providers} from "./components/providers";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
variable : "--font-jetbrains-mono",
  subsets : ["latin"],
}
  )

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jetbrainsMono.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
